Improve multi-tion stability: single-thread worker for communications
TionAPI/HA-tion pull request #63
Opened 2021-12-29 13:42 UTC by kizill

I've encountered problems similar to #60  i have 3 Tion Lite devices and i had two different problems:
1) laggy UI, that hangs due to calling non-async bluetooth & tion device APIs
2) Instable work with devices
Simply putting all the work to 1 threaded job-queue and making async awaits for tasks seems to solve the problems.

2021-12-29 14:45 UTC, IATkachenko commented
Спасибо за PR!

Мне кажется что лучше добавить обертку непосредственно в районе вызовов `__tion.set`/`get`/`connect`/`disconnct` внтури `TionInstance`, без дополнительного класса: непосредственное взаимодействие с бризером осуществляет (по дизайну компонента) именно `TionInstance` плюс это автоматически решит проблему из второо комменатрия к коду.

2021-12-29 14:47 UTC, IATkachenko requested changes

2021-12-29 14:47 UTC, IATkachenko commented on custom_components/tion/__init__.py
> +                raise
Это изменение лучше убрать: оно не связано с целью PR.

2021-12-29 14:47 UTC, IATkachenko commented on custom_components/tion/__init__.py
> +        return ThreadedTionExecutor(Tion(mac))
`getTion` должен вернуть объект типа `tion` (231 строка). Это теперь не выполняется.
Нужно или убрать typehint, или сохранить все свойства/методы `tion` для обертки (что некоторый оверкил).

2022-01-01 13:45 UTC, kizill commented on custom_components/tion/__init__.py
> +        return ThreadedTionExecutor(Tion(mac))
Спасибо! На самом деле хотелось понять в целом ок или не ок подход, решил костыль заслать😄

2022-01-03 17:42 UTC, IATkachenko approved these changes

2022-01-03 17:43 UTC, IATkachenko commented
Спасибо за правки!
В ближайшее время сделаю merge и релиз.

2022-01-04 12:18 UTC, merged